---
title: माझ्या देशाचे मार्गदर्शन ३. ०
hero_image: images/banner.png
description: आपल्या वेबसाइटवर छान लेआउट आणि प्रभावी वैशिष्ठ्ये जोडा!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: सुरुवात अशी करा
  - 
    title: क्लिक करण्या योग्य कार्ड
  - 
    title: एका पंक्तीत
    completion:
      - engaged
  - 
    title: आपला menu प्रतिसाद देणारा करा
  - 
    title: मथळे आणि साइड नोट्स
  - 
    title: छान पृष्ठ लेआउट डिझाइन करा
  - 
    title: छायाचित्रांचा कोलाज
  - 
    title: विशेष प्रभाव
    completion:
      - internal
