---
title: Tour durch mein Land 3.0
hero_image: images/banner.png
description: Füge Deiner Website schöne Layouts und coole Effekte hinzu!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Vorbereitungen
- title: Klickbare Karten
- title: Alles in einer Reihe
  completion:
  - engaged
- title: Lass dein Menu reagieren
- title: Bildunterschriften und Randnotizen
- title: Gestalte coole Seitenlayouts
- title: Fotocollage
- title: Spezialeffekte
  completion:
  - internal
