---
title: Carduri avansate HTML / CSS Sushi
hero_image: images / banner.png
description: Adăugați machete frumoase și efecte interesante pe site-ul dvs.!
theme: roșu
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-JavaScript
site_areas: coderdojo, proiecte
software: html-css-JavaScript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Ce vei avea nevoie
  - 
    title: Noțiuni de bază
  - 
    title: Carduri care pot fi incarcate
  - 
    title: Totul pe rând
  - 
    title: Asigurați-vă că meniul dvs. este receptiv
  - 
    title: Subtitrări și note
  - 
    title: Proiectați machete de pagini răcoroase
  - 
    title: colaj foto
  - 
    title: Efecte speciale
