---
title: دليل لبلادي 3.0
hero_image: images/banner.png
description: أضف تنسيقات جميلة وتأثيرات رائعة إلى موقع الويب الخاص بك!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
- title: المقدمة
  completion: engaged
- title: هيا بنا لنبدأ
- title: بطاقات قابلة للنقر
- title: وضع الكل في صف
- title: اجعل قائمتك قابلة للاستجابة
- title: التسميات التوضيحية والملاحظات الجانبية
- title: تصميم تخطيط صفحة رائع
- title: ملصقات صور
  completion: internal
- title: مؤثرات خاصة
