---
title: 아일랜드 여행 가이드 3.0
hero_image: images/banner.png
description: 웹 사이트에 멋진 레이아웃과 효과를 추가하십시오!
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
technologies: html-css-javascript
site_areas: coderdojo, projects
software: html-css-javascript
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 설정하기
  - 
    title: 클릭 할 수 있는 카드
  - 
    title: 일렬로 세우기
    completion:
      - engaged
  - 
    title: 반응하는 메뉴 만들기
  - 
    title: 설명 및 참조
  - 
    title: 멋진 레이아웃 페이지 디자인
  - 
    title: 사진 콜라주
  - 
    title: 특수 효과
    completion:
      - internal
